### ISSUE TITLE
Option for user to enable/disable Push Notification

### ISSUE THREAD

**Issue by TTPw1nd** [getsocial-im/getsocial-unity-sdk#2]
I'd like to provide an option in my game for user to enable/disable receiving push notification.
I'm thinking about this:

GetSocial has a function, for example named _SetPushNotification(bool)_
This function will tell the server that this user wants to enable/disable receiving push.

I don't know if it's a good solution. Thanks.

**Comment by yral6012** [comment]
Hi Phong, 
I believe you already sent this message on our support channel and its resolved. If you have further questions feel free to message us directly via support.
