### ISSUE TITLE
Android Build Problem - Smart Invites

### ISSUE THREAD

**Issue by carlossdparaujo** [getsocial-im/getsocial-unity-sdk#4]
Hi, I'm having an issue trying to build my project on Android after I added the smart invites settings to my manifest:

![captura de tela 2016-04-25 as 12 15 36](https://cloud.githubusercontent.com/assets/5532253/14788818/135ea4c6-0ae0-11e6-9614-55fc7becc552.png)

I've added the google-play-services_lib folder to my Plugins/Android folder as well, when I try to build the project I get the following error: 

> CommandInvokationFailure:
> 
>  Unable to convert classes into dex format. See the Console for details.
> /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/caraujo/Documents/android-sdk-macosx-2/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -
> 
> stderr[
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.CurrentUser$3) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.CurrentUser$1) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.CurrentUser$5) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.CurrentUser$2) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.CurrentUser$4) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$11) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$11$1) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$12) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$13) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$14) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$15) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$16) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$17) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$2) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$3) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$3$1) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$4) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$5) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$6) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$7) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$8) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$9) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$1) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.GetSocial$10) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.UI.ContentView$1) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.UI.LayerDialogForUnity$1) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.UI.LayerPopupWindow$1) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.UI.ViewBuilder$1) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution is to recompile the class from source, using an up-to-date compiler
> and without specifying any "-target" type options. The consequence of ignoring
> this warning is that reflective operations on this class will incorrectly
> indicate that it is _not_ an inner class.
> warning: Ignoring InnerClasses attribute for an anonymous inner class
> (im.getsocial.sdk.core.UI.ViewBuilder$1$1) that doesn't come with an
> associated EnclosingMethod attribute. This class was probably produced by a
> compiler that did not target the modern .class file format. The recommended
> solution<message  truncated>

Am I missing some configuration step?
Thanks

**Comment by zasadnyy** [comment]
Hello Carlos,

The log is truncated, an actual error is not there.
Did you try to build your project only with GetSocial SDK and without Google Play Services? If not, please try and say if it works.

**Comment by carlossdparaujo** [comment]
When I build it without Google Play Services it works fine, but I need it to track the smart invite installations, right? 
When I add the dependence in the AndroidManifest Unity doesn't build, saying it can't find Google Play Services, if I copy the lib folder to my project it gives me the error I sent before.

**Comment by zasadnyy** [comment]
Сorrect.

This error usually means there is a jar or a set of classes being included multiple times. Could you please check if that there are no duplicates in added jar files?

Also, please make sure you performed initial Google Play Services setup, available via `Window -> Google Play Games -> Setup -> Android setup...`

**Comment by carlossdparaujo** [comment]
I found it! The Facebook plugin we're using had a duplicated .aar file!
Thank you very much!

Just one more question, is there any reason the SmartInvites view wouldn't show on an anonymous user? I'm trying to show it and event though there are providers, the view isn't showing. But when I have a Facebook identity the view always shows normally.

**Comment by zasadnyy** [comment]
> I'm trying to show it and event though there are providers, the view isn't showing 

How did you find that there are providers? Did you see GetSocial view with a list of providers, but clicking on FB provided didn't work? Or GetSocial view didn't show up at all?

Also, please make sure you open a Smart Invites view after `onSuccess` callback was invoked on `GetSocial.init(...)` method

**Comment by carlossdparaujo** [comment]
I printed out the list of providers, the view didn't show up at all. When I call GetSocial.Instance.CreateSmartInviteView().Show() I get this log only:

```
I/Unity   (31178): Serialized view builder: {
I/Unity   (31178):  "viewBuilder":"smartInvite"
I/Unity   (31178): }
I/Unity   (31178):  
I/Unity   (31178): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
I/Unity   (31178): 
W/Unity   (31178): ShowView: GetSocialSdk.Core.ViewBuilder+OnViewActionDelegate
W/Unity   (31178):  
W/Unity   (31178): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
W/Unity   (31178): 
```

But the view doesn't appear, and after I add an user identity (logged in with Facebook) the view appears normally.

Another thing I noticed is that when I have my app installed in a device and Build+Run with Unity over it GetSocial Init always fails.
Is this normal? And is there a way for me to look at the initialization error? The callback doesn't send me one and I'm not finding anything on logcat.

The only errors I get after the Init has failed is when I try to use some of GetSocial's feature and it crashes like:

```
E/AndroidRuntime( 4724): FATAL EXCEPTION: main
E/AndroidRuntime( 4724): Process: com.Gazeus.SNH, PID: 4724
E/AndroidRuntime( 4724): java.lang.Error: FATAL EXCEPTION [main]
E/AndroidRuntime( 4724): Unity version     : 5.3.4f1
E/AndroidRuntime( 4724): Device model      : LGE Nexus 4
E/AndroidRuntime( 4724): Device fingerprint: google/occam/mako:5.1.1/LMY48T/2237560:user/release-keys
E/AndroidRuntime( 4724): 
E/AndroidRuntime( 4724): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void im.getsocial.sdk.core.CurrentUser.addUserIdentity(im.getsocial.sdk.core.UserIdentity, im.getsocial.sdk.core.AddUserIdentityObserver)' on a null object reference
E/AndroidRuntime( 4724):    at im.getsocial.sdk.core.unity.GetSocialUnityBridge$4.run(GetSocialUnityBridge.java:246)
E/AndroidRuntime( 4724):    at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 4724):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 4724):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 4724):    at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 4724):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4724):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4724):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 4724):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/ActivityManager(  561):   Force finishing activity 1 com.Gazeus.SNH/com.unity3d.player.UnityPlayerActivity
```
